### ISSUE TITLE
Adjust paths to work with the Github version of the code

### ISSUE THREAD

**Issue by larsvilhuber** [labordynamicsinstitute/SynUSpopulation#1]
Programs are still referencing code in development locations.

**Comment by sextonw** [comment]
I have a forked version of this project that solves this issue and has other significant improvements to the code but some aspects are still under develop. I will update when completed.

**Comment by larsvilhuber** [comment]
Could you send a pull request so we can get at those parts of the code that solve this problem?

**Comment by sextonw** [comment]
Output paths are fixed. I'm cleaning up the fork today before pulling in that version. This issue is now resolved.

**Comment by larsvilhuber** [comment]
Issue remains open until code is integrated.

**Comment by sextonw** [comment]
Code to fix this issue has been integrated. Code with additional improvements will be integrated ASAP, hopeful today, but I thought that was a separate issue.

**Comment by larsvilhuber** [comment]
Issue did not reference code pull. See aefe48bf6ad2a35ba1a1b836690f007e888977de for fix.
