### ISSUE TITLE
checksums for validation

### ISSUE THREAD

**Issue by sextonw** [labordynamicsinstitute/SynUSpopulation#3]
create checksums for dataLumos archive (all three of them for ACS 5-year PUMS), and release new version of those archives

**Comment by larsvilhuber** [comment]
This is fixed in all three DataLumos deposits we've made:

http://doi.org/10.3886/E100486V2 (2010-2014)
http://doi.org/10.3886/E100521V2 (2011-2015)
http://doi.org/10.3886/E100517V2 (2009-2013)
